# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 250940907a65edea0c4aaee61996fc15ce1746e2d0e8acc5a8418cba815a602dfbef8fdcc82a6171eddb2ab696591ef3abd3b5f1c8bc7b9c4f6aace5c1b2f2ae

test:
  secret_key_base: 34e607caec4e2c665df9df33bcb11312ed8027be18a9056120948e08bc1cf8dc8c74ead83fe19d094fd553ecab009f7d728e7afeba0d3bd13529fd0cb4324111

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
